"""empty message

Revision ID: 024afd2401be
Revises: 180579c756b4
Create Date: 2018-11-30 16:02:06.959170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024afd2401be'
down_revision = '180579c756b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intrest')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intrest',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('intrest_type', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
