"""empty message

Revision ID: 180579c756b4
Revises: dc9617df55ef
Create Date: 2018-11-30 15:46:38.690574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180579c756b4'
down_revision = 'dc9617df55ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=True),
    sa.Column('event_description', sa.String(), nullable=True),
    sa.Column('event_location', sa.String(), nullable=True),
    sa.Column('event_start_date', sa.DateTime(), nullable=True),
    sa.Column('event_end_date', sa.DateTime(), nullable=True),
    sa.Column('event_status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_end_date'), 'events', ['event_end_date'], unique=False)
    op.create_index(op.f('ix_events_event_start_date'), 'events', ['event_start_date'], unique=False)
    op.create_table('occupation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('occupation_name', sa.Text(), nullable=True),
    sa.Column('occupation_company', sa.Text(), nullable=True),
    sa.Column('occupation_start_date', sa.DateTime(), nullable=True),
    sa.Column('occupation_end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_occupation_occupation_end_date'), 'occupation', ['occupation_end_date'], unique=False)
    op.create_index(op.f('ix_occupation_occupation_start_date'), 'occupation', ['occupation_start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_occupation_occupation_start_date'), table_name='occupation')
    op.drop_index(op.f('ix_occupation_occupation_end_date'), table_name='occupation')
    op.drop_table('occupation')
    op.drop_index(op.f('ix_events_event_start_date'), table_name='events')
    op.drop_index(op.f('ix_events_event_end_date'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
