"""empty message

Revision ID: 34c19e023e91
Revises: 0961350fe18f
Create Date: 2018-11-30 23:43:51.604664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c19e023e91'
down_revision = '0961350fe18f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blog_city', sa.String(length=50), nullable=False),
    sa.Column('blog_category', sa.String(length=50), nullable=False),
    sa.Column('blog_story_line', sa.String(length=500), nullable=False),
    sa.Column('blog_story_text', sa.Text(), nullable=False),
    sa.Column('blog_youtube_link', sa.String(length=500), nullable=True),
    sa.Column('blog_date_posted', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blogcomments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blogcomments_timestamp'), 'blogcomments', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blogcomments_timestamp'), table_name='blogcomments')
    op.drop_table('blogcomments')
    op.drop_table('blog')
    # ### end Alembic commands ###
