"""empty message

Revision ID: 85a2dc63dde3
Revises: d4a2bec0fb4b
Create Date: 2018-11-30 16:34:44.321138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a2dc63dde3'
down_revision = 'd4a2bec0fb4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intrest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('intrest_name', sa.Text(), nullable=True),
    sa.Column('intrest_type', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intrest')
    # ### end Alembic commands ###
