"""empty message

Revision ID: 98902a22c075
Revises: 8fb996f9cc12
Create Date: 2018-11-30 16:07:23.064687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98902a22c075'
down_revision = '8fb996f9cc12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intrest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('intrest_type', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intrest')
    # ### end Alembic commands ###
