"""new fields in user model

Revision ID: ae2f4cfaf755
Revises: dc480dede1b1
Create Date: 2018-11-26 01:02:22.541995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae2f4cfaf755'
down_revision = 'dc480dede1b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('social_id', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'social_id')
    # ### end Alembic commands ###
