"""empty message

Revision ID: dc9617df55ef
Revises: ae2f4cfaf755
Create Date: 2018-11-30 15:39:20.879910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9617df55ef'
down_revision = 'ae2f4cfaf755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_event_end_date', table_name='events')
    op.drop_index('ix_events_event_start_date', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_occupation_occupation_end_date', table_name='occupation')
    op.drop_index('ix_occupation_occupation_start_date', table_name='occupation')
    op.drop_table('occupation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occupation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('occupation_name', sa.TEXT(), nullable=True),
    sa.Column('occupation_description', sa.TEXT(), nullable=True),
    sa.Column('occupation_start_date', sa.DATETIME(), nullable=True),
    sa.Column('occupation_end_date', sa.DATETIME(), nullable=True),
    sa.Column('ocumpation_compay', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_occupation_occupation_start_date', 'occupation', ['occupation_start_date'], unique=False)
    op.create_index('ix_occupation_occupation_end_date', 'occupation', ['occupation_end_date'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('event_name', sa.VARCHAR(), nullable=True),
    sa.Column('event_description', sa.VARCHAR(), nullable=True),
    sa.Column('event_location', sa.VARCHAR(), nullable=True),
    sa.Column('event_start_date', sa.DATETIME(), nullable=True),
    sa.Column('event_end_date', sa.DATETIME(), nullable=True),
    sa.Column('event_status', sa.BOOLEAN(), nullable=True),
    sa.Column('media_id', sa.INTEGER(), nullable=False),
    sa.CheckConstraint('event_status IN (0, 1)'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_event_start_date', 'events', ['event_start_date'], unique=False)
    op.create_index('ix_events_event_end_date', 'events', ['event_end_date'], unique=False)
    # ### end Alembic commands ###
